### ISSUE TITLE
Put variable name and value text box entry on same line

### ISSUE THREAD

**Issue by BCS-JonW** [lawn-chair/bcs-recipes#3]
"Recipe Values" entry needs to be more compact.  When using several entries in the "Recipe Values" screen, the entries quickly scroll down the page because of the stacked nature of the elements.  Each entry should be a single line similar to the "Variable Setup" screen.

**Comment by lawn-chair** [comment]
fixed in 14b1df3eff653350caaee9c3bcb72e178a07defb
